# Generated by Django 4.2.11 on 2024-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fname", models.CharField(max_length=100)),
                ("cnic", models.CharField(max_length=15, unique=True)),
                ("personalno", models.CharField(max_length=50, unique=True)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("SST Arts", "SST Arts"),
                            ("SST MATH", "SST MATH"),
                            ("SST BIO", "SST BIOLOGY"),
                            ("SST PHY", "SST PHYSICS"),
                            ("SST CHE", "SST CHEMISTRY"),
                            ("SST IT", "SST COMPUTER"),
                            ("EST Arts", "EST Arts"),
                            ("EST Sci", "EST Science"),
                            ("EST Arts", "EST Arts"),
                            ("EST Agri", "EST Agri"),
                            ("EST General", "EST General"),
                            ("EST Vr", "EST Vernacular"),
                            ("PST Sci", "PST Science"),
                            ("PST Arts", "PST Arts"),
                            ("PST", "PST"),
                            ("Naib Qasid", "Naib Qasid"),
                            ("L.Attendant", "Lab Attendant"),
                            ("Mali", "Mali"),
                            ("C.IV", "Class 4"),
                            ("SG", "Security Guard"),
                            ("Chokidat", "Chokidar"),
                            ("Sweaper", "Sweaper"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scale",
                    models.CharField(
                        choices=[
                            ("19", "19"),
                            ("18", "18"),
                            ("17", "17"),
                            ("16", "16"),
                            ("15", "15"),
                            ("14", "14"),
                            ("12", "12"),
                            ("9", "9"),
                            ("7", "7"),
                            ("5", "5"),
                            ("4", "4"),
                            ("3", "3"),
                            ("2", "2"),
                            ("1", "1"),
                        ],
                        max_length=3,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("date_of_first_joining", models.DateField()),
                ("date_of_joining_present_scale", models.DateField()),
                ("date_of_joining_present_school", models.DateField()),
                ("accountno", models.CharField(max_length=50, unique=True)),
                ("bank", models.CharField(max_length=100)),
                ("phoneno", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
