# Generated by Django 4.2.11 on 2024-10-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoolapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_no", models.CharField(max_length=20, unique=True)),
                ("admission_date", models.DateField()),
                ("name", models.CharField(max_length=100)),
                ("fathername", models.CharField(max_length=100)),
                ("b_form_no", models.CharField(max_length=15, unique=True)),
                ("contact_no", models.CharField(max_length=15)),
                (
                    "class_enrolled",
                    models.CharField(
                        choices=[
                            ("Nursery", "Nursery"),
                            ("KG", "Kindergarten"),
                            ("1", "Class 1"),
                            ("2", "Class 2"),
                            ("3", "Class 3"),
                            ("4", "Class 4"),
                            ("5", "Class 5"),
                            ("6", "Class 6"),
                            ("7", "Class 7"),
                            ("8", "Class 8"),
                            ("9", "Class 9"),
                            ("10", "Class 8"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
            ],
        ),
    ]
