# Generated by Django 4.2.11 on 2024-10-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoolapp", "0002_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(default="", upload_to="shoolapp/images"),
        ),
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(default="", upload_to="shoolapp/images"),
        ),
    ]
